theme: jekyll-theme-dinky
title: Basket Recorder Pro Tutorial
description: Guida introduttiva a Basket Recorder Pro
show_downloads: false
itunes_url: https://itunes.apple.com/it/app/basket-recorder-pro/id590251773?l=it&ls=1&mt=8
